name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: CI
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test:ci
